from etl_service.domain.models import ImportSpec


IMPORT_SPECS: dict[str, ImportSpec] = {
    "companies": ImportSpec(
        import_type="companies",
        staging_table="staging_companies",
        staging_pk="staging_companies_id",
        dw_table="companies",
        dw_pk="company_id",
        columns=("company_id", "name", "is_active"),
        required_fields=("name",),
        lookup_groups=(("name",),),
        force_company_id=False,
        default_values={"is_active": True},
    ),
    "branches": ImportSpec(
        import_type="branches",
        staging_table="staging_branches",
        staging_pk="staging_branches_id",
        dw_table="branches",
        dw_pk="branch_id",
        columns=("branch_id", "company_id", "name", "code", "address", "city", "phone", "is_active"),
        required_fields=("company_id", "name"),
        lookup_groups=(("company_id", "code"), ("company_id", "name")),
        default_values={"is_active": True},
    ),
    "categories": ImportSpec(
        import_type="categories",
        staging_table="staging_categories",
        staging_pk="staging_categories_id",
        dw_table="categories",
        dw_pk="category_id",
        columns=(
            "category_id",
            "company_id",
            "parent_category_id",
            "name",
            "description",
            "display_order",
            "is_active",
        ),
        required_fields=("company_id", "name"),
        lookup_groups=(("company_id", "name"),),
        default_values={"is_active": True},
    ),
    "customers": ImportSpec(
        import_type="customers",
        staging_table="staging_customers",
        staging_pk="staging_customers_id",
        dw_table="customers",
        dw_pk="customer_id",
        columns=(
            "customer_id",
            "company_id",
            "customer_type",
            "erp_customer_code",
            "tax_id",
            "name",
            "contact_name",
            "contact_email",
            "contact_phone",
            "contact_mobile",
            "billing_address",
            "is_active",
            "notes",
        ),
        required_fields=("company_id", "customer_type", "name"),
        lookup_groups=(("company_id", "erp_customer_code"), ("company_id", "tax_id"), ("company_id", "name")),
        enum_fields={"customer_type": ("INDIVIDUAL", "BUSINESS")},
        default_values={"is_active": True},
    ),
    "suppliers": ImportSpec(
        import_type="suppliers",
        staging_table="staging_suppliers",
        staging_pk="staging_suppliers_id",
        dw_table="suppliers",
        dw_pk="supplier_id",
        columns=("supplier_id", "company_id", "erp_supplier_code", "name", "is_active"),
        required_fields=("company_id", "name"),
        lookup_groups=(("company_id", "erp_supplier_code"), ("company_id", "name")),
        default_values={"is_active": True},
    ),
    "products": ImportSpec(
        import_type="products",
        staging_table="staging_products",
        staging_pk="staging_products_id",
        dw_table="products",
        dw_pk="product_id",
        columns=(
            "product_id",
            "company_id",
            "category_id",
            "supplier_id_fk",
            "erp_product_code",
            "sku",
            "barcode",
            "name",
            "description",
            "unit_of_measure",
            "cost_price",
            "sale_price",
            "min_stock",
            "max_stock",
            "reorder_point",
            "is_active",
            "category_abc",
            "is_taxable",
            "tax_rate",
        ),
        required_fields=("company_id", "category_id", "sku", "name", "unit_of_measure"),
        lookup_groups=(("sku",), ("company_id", "erp_product_code")),
        enum_fields={"unit_of_measure": ("UNIT", "KG", "L", "M", "BOX", "PACK")},
        default_values={
            "cost_price": 0,
            "sale_price": 0,
            "min_stock": 0,
            "max_stock": 0,
            "is_active": True,
            "is_taxable": True,
            "tax_rate": 0,
        },
    ),
    "product_suppliers": ImportSpec(
        import_type="product_suppliers",
        staging_table="staging_product_suppliers",
        staging_pk="staging_product_suppliers_id",
        dw_table="product_suppliers",
        dw_pk="product_suppliers_id",
        columns=("product_suppliers_id", "product_id", "supplier_id", "is_primary", "is_active", "priority"),
        required_fields=("product_id", "supplier_id"),
        lookup_groups=(("product_id", "supplier_id"),),
        default_values={"is_primary": False, "is_active": True},
        force_company_id=False,
    ),
    "purchases": ImportSpec(
        import_type="purchases",
        staging_table="staging_purchases",
        staging_pk="staging_purchases_id",
        dw_table="purchases",
        dw_pk="purchases_id",
        columns=(
            "purchases_id",
            "company_id",
            "supplier_id",
            "branch_id",
            "purchase_order_number",
            "purchase_date",
            "expected_delivery_date",
            "received_date",
            "invoice_number",
            "status",
            "payment_method",
            "payment_status",
            "payment_due_date",
            "subtotal",
            "tax_amount",
            "total_amount",
            "notes",
        ),
        required_fields=(
            "company_id",
            "supplier_id",
            "branch_id",
            "purchase_order_number",
            "purchase_date",
            "payment_method",
        ),
        lookup_groups=(("company_id", "purchase_order_number"),),
        enum_fields={
            "status": ("DRAFT", "CONFIRMED", "RECEIVED", "CANCELLED"),
            "payment_method": ("CASH", "CARD", "TRANSFER", "CREDIT"),
            "payment_status": ("PENDING", "PARTIAL", "PAID"),
        },
        default_values={"status": "DRAFT", "payment_status": "PENDING", "subtotal": 0, "tax_amount": 0, "total_amount": 0},
    ),
    "purchase_details": ImportSpec(
        import_type="purchase_details",
        staging_table="staging_purchases_details",
        staging_pk="staging_purchases_details_id",
        dw_table="purchase_details",
        dw_pk="purchase_detail_id",
        columns=(
            "purchase_detail_id",
            "purchase_id",
            "product_id",
            "quantity_ordered",
            "quantity_received",
            "unit_price",
            "discount_percent",
            "subtotal",
            "tax_amount",
            "total",
            "notes",
        ),
        required_fields=("purchase_id", "product_id"),
        lookup_groups=(),
        default_values={
            "quantity_ordered": 0,
            "quantity_received": 0,
            "unit_price": 0,
            "discount_percent": 0,
            "subtotal": 0,
            "tax_amount": 0,
            "total": 0,
        },
        force_company_id=False,
    ),
    "sales": ImportSpec(
        import_type="sales",
        staging_table="staging_sales",
        staging_pk="staging_sales_id",
        dw_table="sales",
        dw_pk="sales_id",
        columns=(
            "sales_id",
            "company_id",
            "customer_id",
            "branch_id",
            "sale_date",
            "invoice_number",
            "status",
            "payment_method",
            "payment_status",
            "subtotal",
            "tax_amount",
            "discount_amount",
            "total_amount",
            "notes",
        ),
        required_fields=("company_id", "customer_id", "branch_id", "sale_date", "invoice_number", "payment_method"),
        lookup_groups=(("invoice_number",),),
        enum_fields={
            "status": ("DRAFT", "CONFIRMED", "CANCELLED"),
            "payment_method": ("CASH", "CARD", "TRANSFER", "CREDIT"),
            "payment_status": ("PENDING", "PARTIAL", "PAID"),
        },
        default_values={
            "status": "DRAFT",
            "payment_status": "PENDING",
            "subtotal": 0,
            "tax_amount": 0,
            "discount_amount": 0,
            "total_amount": 0,
        },
    ),
    "sales_details": ImportSpec(
        import_type="sales_details",
        staging_table="staging_sales_details",
        staging_pk="staging_sales_details_id",
        dw_table="sales_details",
        dw_pk="sales_details_id",
        columns=(
            "sales_details_id",
            "sales_id",
            "product_id",
            "quantity",
            "unit_cost",
            "unit_price",
            "discount_percent",
            "subtotal",
            "cost_total",
            "profit_amount",
            "profit_margin_percent",
            "tax_amount",
            "total",
        ),
        required_fields=("sales_id", "product_id"),
        lookup_groups=(),
        default_values={
            "quantity": 1,
            "unit_cost": 0,
            "unit_price": 0,
            "discount_percent": 0,
            "subtotal": 0,
            "cost_total": 0,
            "profit_amount": 0,
            "profit_margin_percent": 0,
            "tax_amount": 0,
            "total": 0,
        },
        force_company_id=False,
    ),
    "inventory": ImportSpec(
        import_type="inventory",
        staging_table="staging_inventory",
        staging_pk="staging_inventory_id",
        dw_table="inventory",
        dw_pk="inventory_id",
        columns=(
            "inventory_id",
            "product_id_fk",
            "branch_id_fk",
            "company_id_fk",
            "initial_count",
            "final_count",
            "is_closed",
            "closed_at",
            "closed_by",
            "start_date",
            "end_date",
        ),
        required_fields=("product_id_fk", "branch_id_fk", "company_id_fk", "initial_count", "start_date", "end_date"),
        lookup_groups=(("product_id_fk", "branch_id_fk", "start_date", "end_date"),),
        default_values={"is_closed": False},
        force_company_id=False,
    ),
    "inventory_movement": ImportSpec(
        import_type="inventory_movement",
        staging_table="staging_inventory_movement",
        staging_pk="staging_inventory_movement_id",
        dw_table="inventory_movement",
        dw_pk="movement_id",
        columns=(
            "movement_id",
            "inventory_id_fk",
            "product_id_fk",
            "movement_type",
            "reference_type",
            "quantity",
            "unit_cost",
            "previous_stock",
            "new_stock",
            "notes",
            "created_by",
        ),
        required_fields=(
            "inventory_id_fk",
            "movement_type",
            "reference_type",
            "quantity",
            "unit_cost",
            "previous_stock",
            "new_stock",
            "created_by",
        ),
        lookup_groups=(),
        enum_fields={
            "movement_type": ("IN", "OUT", "ABJUSTMENT", "T"),
            "reference_type": ("SALE", "PURCHASE", "ABJUSTMENT"),
        },
        force_company_id=False,
    ),
}

# Compatibility with the name used in the notes.
IMPORT_SPECS["purchases_details"] = IMPORT_SPECS["purchase_details"]


def get_import_spec(import_type: str) -> ImportSpec:
    key = import_type.strip().lower()
    if key not in IMPORT_SPECS:
        supported = ", ".join(sorted(IMPORT_SPECS))
        raise ValueError(f"Unsupported import_type {import_type!r}. Supported: {supported}")
    return IMPORT_SPECS[key]
